export { default as UserInfo } from './UserInfo'
export { default as Menu } from './Menu'
export { default as AboutProducts } from './AboutProducts'
export { default as Main } from './Main'
export { default as ProductsBlock } from './ProductsBlock'
export { default as ProductsBlock_v2 } from './ProductsBlock_v2'
export { default as SearchHeader } from './SearchHeader'